# Drone Tracker
BASE = "measurement"  # pos, measurement

FIRST_UPDATES_SKIPPED = 5

FILTER_ENABLED = True
FILTER_TYPE = "KF"  # MA (Moving Average), KF (Kalman Filter), EKF (Extended Kalman Filter)

NON_OUTLIER_MIN, NON_OUTLIER_MAX = 0, 5
OUTLIER_REJECTION_ENABLED = True
OUTLIER_INTERPOLATION_ENABLED = True  # True: Quad interpolation, False: Rely on Filter

MEASURE_VARIANCE = True
VARIANCE_SIZE = 5

ORCHESTRATOR_DELAY = 0.05

# Multilateration settings
USE_LAST_POS = True

# MA settings
MOVING_AVG_FILTER_RATE = 0.9

# Simulator
SIMULATOR_FREQUENCY = 10
TRAJECTORY_PERCENTAGE_CHANGE = 0.01

ADD_GAUSSIAN_NOISE = True
GAUSSIAN_NOISE_MEAN = 0.0
GAUSSIAN_NOISE_STD = 0.1

OUTLIER_INJECTION_ENABLED = True
OUTLIER_INJECTION_MIN, OUTLIER_INJECTION_MAX = -327, 327
OUTLIER_INJECTION_PROBABILITY = 0.30

# Visualizer
PLOT_GROUND_TRUTH = True
PLOT_ERROR_MIN = 0.15  # 15 cm
